version: '3.8'

services:
  users-db:
    image: postgres:latest
    container_name: microsservico_users_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microsservico_users
    volumes:
      - users_db_data:/var/lib/postgresql/data

volumes:
  users_db_data:
